import os
import uuid

# Isolated SQLite test DB
test_db_filename = f"./test_ai_exec_{uuid.uuid4().hex[:8]}.db"
os.environ["DATABASE_URL"] = f"sqlite:///{test_db_filename}"

from fastapi.testclient import TestClient
from app.main import app

client = TestClient(app)

def test_central_ai_execution_router():
    print("--- 1. Registering User to get Auth Token ---")
    reg_payload = {
        "email": f"ai_exec_admin_{uuid.uuid4().hex[:6]}@company.com",
        "password": "SecretPassword123",
        "full_name": "AI Executive Admin",
        "company_name": "AI Executive Corp"
    }
    reg_resp = client.post("/api/v1/auth/register", json=reg_payload)
    assert reg_resp.status_code == 201, f"User registration failed: {reg_resp.text}"
    auth_token = reg_resp.json()["access_token"]
    headers = {"Authorization": f"Bearer {auth_token}"}
    print("Auth Token obtained successfully!")

    print("\n--- 2. Listing Available AI Tools ---")
    tools_resp = client.get("/api/v1/ai/tools", headers=headers)
    assert tools_resp.status_code == 200
    tools_list = tools_resp.json()["tools"]
    print("Available AI Tools:", tools_list)
    assert "create_customer" in tools_list
    assert "create_invoice" in tools_list
    assert "generate_quotation" in tools_list
    assert "send_email" in tools_list

    print("\n--- 3. Executing AI Tool: create_customer ---")
    cust_exec_payload = {
        "tool_name": "create_customer",
        "parameters": {
            "name": "Acme AI Client",
            "email": "acme_ai@test.com",
            "phone": "+18005550199",
            "company_name": "Acme AI Corp"
        }
    }
    cust_exec_resp = client.post("/api/v1/ai/execute", json=cust_exec_payload, headers=headers)
    print("AI Create Customer Status Code:", cust_exec_resp.status_code)
    assert cust_exec_resp.status_code == 200
    cust_data = cust_exec_resp.json()
    assert cust_data["success"] is True
    customer_id = cust_data["result"]["id"]
    print("Created Customer via AI Router ID:", customer_id)

    print("\n--- 4. Executing AI Tool: create_task ---")
    task_exec_payload = {
        "tool_name": "create_task",
        "parameters": {
            "title": "AI Onboarding Review",
            "description": "Follow up with Acme AI Client for system demo",
            "priority": "high"
        }
    }
    task_exec_resp = client.post("/api/v1/ai/execute", json=task_exec_payload, headers=headers)
    print("AI Create Task Status Code:", task_exec_resp.status_code)
    assert task_exec_resp.status_code == 200
    assert task_exec_resp.json()["success"] is True
    print("Task Creation via AI Router Verification: PASSED!")

    print("\n--- 5. Executing AI Tool: generate_quotation ---")
    qtn_exec_payload = {
        "tool_name": "generate_quotation",
        "parameters": {
            "customer_id": customer_id,
            "tax_percent": 10.0,
            "discount_percent": 5.0,
            "currency": "USD",
            "notes": "Generated by Central AI Executive",
            "line_items": [
                {"description": "AI License Suite", "quantity": 1, "unit_price": 3000.0}
            ]
        }
    }
    qtn_exec_resp = client.post("/api/v1/ai/execute", json=qtn_exec_payload, headers=headers)
    print("AI Generate Quotation Status Code:", qtn_exec_resp.status_code)
    assert qtn_exec_resp.status_code == 200
    assert qtn_exec_resp.json()["success"] is True
    quotation_id = qtn_exec_resp.json()["result"]["id"]
    print("Quotation Generated via AI Router ID:", quotation_id)

    print("\n--- 6. Executing AI Tool: create_invoice ---")
    inv_exec_payload = {
        "tool_name": "create_invoice",
        "parameters": {
            "customer_id": customer_id,
            "tax_percent": 10.0,
            "discount_percent": 5.0,
            "currency": "USD",
            "notes": "Generated by Central AI Executive",
            "line_items": [
                {"description": "Enterprise AI Server Package", "quantity": 1, "unit_price": 6000.0}
            ]
        }
    }
    inv_exec_resp = client.post("/api/v1/ai/execute", json=inv_exec_payload, headers=headers)
    print("AI Create Invoice Status Code:", inv_exec_resp.status_code)
    assert inv_exec_resp.status_code == 200
    assert inv_exec_resp.json()["success"] is True
    invoice_id = inv_exec_resp.json()["result"]["id"]
    print("Invoice Created via AI Router ID:", invoice_id)

    print("\n--- 7. Executing AI Tool: send_email ---")
    email_exec_payload = {
        "tool_name": "send_email",
        "parameters": {
            "to_email": "acme_billing@test.com",
            "subject": "Your AI Employee OS Invoice & Quotation Package",
            "body_html": "<p>Dear Acme Team,</p><p>Please review your generated invoice & quotation.</p>"
        }
    }
    email_exec_resp = client.post("/api/v1/ai/execute", json=email_exec_payload, headers=headers)
    print("AI Send Email Status Code:", email_exec_resp.status_code)
    assert email_exec_resp.status_code == 200
    assert email_exec_resp.json()["success"] is True
    print("Email Sent via AI Router Verification: PASSED!")

    print("\n--- 8. Verifying System Audit Trail for AI Executions ---")
    audit_resp = client.get("/api/v1/audit-logs?actor_type=ai", headers=headers)
    assert audit_resp.status_code == 200
    res_json = audit_resp.json()
    audit_logs = res_json if isinstance(res_json, list) else res_json.get("items", [])
    print(f"Total AI Audit Logs Recorded: {len(audit_logs)}")
    assert len(audit_logs) >= 5
    print("Audit Log Verification: PASSED!")

    print("\nSUCCESS! Central AI Action Execution Router (/api/v1/ai/execute) is 100% fully functional!")

if __name__ == "__main__":
    try:
        test_central_ai_execution_router()
    finally:
        if os.path.exists(test_db_filename):
            try:
                os.remove(test_db_filename)
            except Exception:
                pass
