"""create company user ai_employee invoice quotation task meeting document tables

Revision ID: 905ebbb9c568
Revises: ebb1baf6abb7
Create Date: 2026-08-03 16:27:15.916991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '905ebbb9c568'
down_revision: Union[str, Sequence[str], None] = 'ebb1baf6abb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
